### PR TITLE
Add GitHub action to run jest, chromatic and cypress

### PR DESCRIPTION
**Pull request by winkerVSbecks**

### CODE REVIEW

**Comment by AndysonDK** [comment]
I have a question, how is it that the github workflow event is `push` and not `pull request` for the commits in this pull request?

**Comment by winkerVSbecks** [comment]
https://www.chromatic.com/docs/cli#usage-in-a-github-action

In general, the git history is an important for making Chromatic work as expected. That's how it figures out correct baselines. The gist of the issue is that PRs create a merge commit which don't persist in history. 

You could break this into two workflows. Run Chromatic on push and the rest on pull_request

**Comment by AndysonDK** [comment]
Got it thanks! Also do you think it'll work if I specify specific [paths ](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths) where I want chromatic to run? Could it mess with PR checks? I could imagine a scenario where if a contributor commits one commit containing a UI change (changes that are caught by the specific [paths](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths)), and then later commits something that doesn't contain anything specified in the [paths](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths), then there will be no chromatic PR checks in the PR tab on that latter commit. That could be a problem I think:
Here is an example that use the [paths ](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths) syntax:
https://github.com/AndysonDK/syncbase/blob/5522fac1160b42f4081a396023f98db115dcf7c1/.github/workflows/ui_tests.yml

**Comment by winkerVSbecks** [comment]
That usually doesn't work because you do need Chromatic to run consistently. A better option is to use the [turbosnap](https://www.chromatic.com/docs/turbosnap.html#turbosnap) feature. It analyses the build to see if a dependency of a story was updates and if so, then it snapshots it.

**Comment by AndysonDK** [comment]
I could also use the `skip` option on the [Chromatic Action](https://github.com/chromaui/action) combined with [paths filter action](https://github.com/dorny/paths-filter) and then pass true to the skip option when the correct files have changed. Do you think that could work 😄

**Comment by winkerVSbecks** [comment]
Yea, that works so. The main thing to keep in mind is that, when do run chromatic, run it on all stories. Don't skip any stories manually.

**Pull request closed without merging**
